<a href="https://colab.research.google.com/github/JoelAbadi/DI-Bootcamp/blob/main/W4_D1_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 1


In [1]:
import numpy as np


1


In [2]:
array_1 = np.arange(10)
print(array_1)


[0 1 2 3 4 5 6 7 8 9]


2

In [3]:
list_2 = [3.14, 2.17, 0, 1, 2]
array_2 = np.array(list_2, dtype=int)
print(array_2)


[3 2 0 1 2]


3

In [4]:
array_3 = np.arange(1, 10).reshape(3, 3)
print(array_3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


4

In [5]:
array_4 = np.random.rand(4, 5)
print(np.round(array_4, 2))  # Round for cleaner output


[[0.02 0.96 0.44 0.73 0.1 ]
 [0.39 0.01 0.46 0.11 0.17]
 [0.1  0.26 0.81 0.04 0.21]
 [0.79 0.91 0.52 0.37 0.2 ]]


5

In [6]:
array_5 = np.array([[21,22,23,22,22],
                    [20,21,22,23,24],
                    [21,22,23,22,22]])
second_row = array_5[1]
print(second_row)


[20 21 22 23 24]


6

In [7]:
array_6 = np.arange(10)
reversed_array = array_6[::-1]
print(reversed_array)


[9 8 7 6 5 4 3 2 1 0]


7

In [8]:
identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


8

In [9]:
array_8 = np.arange(10)
total_sum = np.sum(array_8)
average = np.mean(array_8)
print("Sum:", total_sum)
print("Average:", average)


Sum: 45
Average: 4.5


9

In [10]:
array_9 = np.arange(1, 21).reshape(4, 5)
print(array_9)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


10

In [11]:
array_10 = np.arange(10)
odd_numbers = array_10[array_10 % 2 == 1]
print(odd_numbers)


[1 3 5 7 9]
